import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const ROOT=path.dirname(fileURLToPath(import.meta.url));
export async function review(root=ROOT) {
 const data=JSON.parse(await fs.readFile(path.join(root,'artwork_candidates.json'),'utf8'));
 const payload=JSON.stringify(data).replace(/</g,'\\u003c');
 const html=`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>yamazo Artwork Review</title>
 <style>body{max-width:1400px;font:16px system-ui;margin:24px;background:#f4f4f1;color:#222}header{position:sticky;top:0;background:#f4f4f1;padding:12px 0;z-index:1}button,select,input{padding:10px;margin:4px;max-width:100%}article{background:white;padding:20px;margin:20px 0;border-radius:8px}.grid{display:flex;gap:16px;flex-wrap:wrap}.candidate{width:270px;border:1px solid #ccc;padding:12px;overflow-wrap:anywhere}.candidate img{width:100%;height:220px;object-fit:contain}small{display:block}pre{white-space:pre-wrap;overflow-wrap:anywhere}a{color:#2459ab}li{margin:6px 0}details{margin:12px 0;font-size:13px}@media(max-width:600px){body{margin:12px}header{position:static}.candidate{width:100%;box-sizing:border-box}article{padding:12px}}</style>
 <header><h1>Works画像の候補確認</h1><p id="summary"></p><select id="filter"><option value="all">すべて</option><option value="auto_eligible">高確度</option><option value="review">承認待ち</option><option value="hold">保留</option><option value="empty">候補なし</option></select><input id="search" placeholder="作品名・アーティスト"><button id="export">選択した承認JSONを保存</button><span id="count"></span><p>初期選択はすべて保留。画像と出典を確認して採用を選んでください。スコアは正解確率ではありません。</p></header><details id="exported" hidden><summary>承認JSON（保存できない場合はここからコピー）</summary><textarea id="decisions-output" readonly aria-label="承認JSON" style="width:100%;height:200px;box-sizing:border-box"></textarea></details><main id="rows"></main>
 <script type="application/json" id="data">${payload}</script><script>
 const data=JSON.parse(document.getElementById('data').textContent),selected=new Map(),rows=document.getElementById('rows');
 const el=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e};
 function safe(v){try{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password?u.href:''}catch{return ''}}
 const labels={title_exact:'タイトル一致',title_presentation_normalized:'補助表記を除いて一致',artist_exact:'アーティスト一致',artist_component_exact:'アーティストの一部が一致',year_exact:'年一致',year_mismatch:'年が不一致',category_compatible:'カテゴリ整合',explicit_identity:'既存ID一致',recording_release_membership:'収録リリース確認',stored_source_page:'登録済み出典ページ',page_title_contains:'ページタイトルに作品名',title_mismatch:'タイトル相違'};
 const stats=data.summary||{};document.getElementById('summary').textContent='候補あり '+(stats.with_candidates??'—')+'件 ／ 高確度 '+(stats.auto_eligible??'—')+'件 ／ 承認待ち '+(stats.review??'—')+'件 ／ 保留のみ '+(stats.hold_only??'—')+'件 ／ 候補なし '+(stats.without_candidates??'—')+'件';
 function draw(){rows.replaceChildren();const filter=document.getElementById('filter').value,q=document.getElementById('search').value.toLowerCase();
 for(const row of data.items){if(q&&!JSON.stringify([row.title,row.artist]).toLowerCase().includes(q))continue;if(filter==='empty'&&row.suggestions.length)continue;if(!['all','empty'].includes(filter)&&!row.suggestions.some(s=>s.status===filter))continue;
 const article=el('article');article.append(el('h2',row.title),el('p',[row.artist,row.year,row.work_id].filter(Boolean).join(' / ')));
 const reset=el('button','選択解除・保留');reset.onclick=()=>{selected.delete(row.work_id);draw()};article.append(reset);
 const grid=el('div');grid.className='grid';for(const s of row.suggestions){const card=el('div');card.className='candidate';const img=el('img');img.src=safe(s.artwork.src);img.loading='lazy';img.referrerPolicy='no-referrer';img.alt=s.title;img.onerror=()=>{img.alt='画像を読み込めません。出典を確認してください'};card.append(img,el('h3',s.title),el('p',s.artist+' / '+(s.year||'年不明')),el('strong',s.confidence+' · '+s.status));const link=el('a','出典を開く');link.href=safe(s.source_url);link.target='_blank';link.rel='noreferrer';card.append(el('p',s.release_title),link);const evidence=el('ul');for(const e of s.evidence)evidence.append(el('li',(labels[e.code]||e.code)+' ('+(e.points>0?'+':'')+e.points+')'));card.append(evidence);const detail=el('details');detail.append(el('summary','根拠・保留理由・画像検査の詳細'),el('pre',JSON.stringify({evidence:s.evidence,blockers:s.blockers,image_validation:s.image_validation||'未検査'},null,2)));card.append(detail);const label=el('label'),radio=el('input');radio.type='radio';radio.disabled=s.image_validation?.ok===false;radio.name=row.work_id;radio.checked=selected.get(row.work_id)===s.id;radio.onchange=()=>{selected.set(row.work_id,s.id);document.getElementById('count').textContent=selected.size+'件選択'};label.append(radio,document.createTextNode('この画像を採用'));card.append(label);grid.append(card)}article.append(grid);if(!row.suggestions.length)article.append(el('p','候補なし'));if(row.errors.length)article.append(el('pre',JSON.stringify(row.errors,null,2)));rows.append(article)}document.getElementById('count').textContent=selected.size+'件選択'}
 document.getElementById('filter').onchange=draw;document.getElementById('search').oninput=draw;
 document.getElementById('export').onclick=()=>{const decisions=[...selected].map(([work_id,suggestion_id])=>({work_id,decision:'accept',suggestion_id}));const output=JSON.stringify(decisions,null,2)+'\\n';document.getElementById('decisions-output').value=output;document.getElementById('exported').hidden=false;document.getElementById('exported').open=true;const url=URL.createObjectURL(new Blob([output],{type:'application/json'}));const a=el('a');a.href=url;a.download='artwork_decisions.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)};draw();</script></html>`;
 await fs.writeFile(path.join(root,'artwork-review.html'),html);console.log('Created artwork-review.html');
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)) review().catch(e=>{console.error(e);process.exitCode=1;});
